name: "Report a Bug 🐛"
description: Report a bug or issue.
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: "Extension Version"
      description: Check in your browser at chrome:extensions or about:addons
      placeholder: "2.1.0"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter a description of your issue
      placeholder: Include a detailed description and screenshots...
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: "Browsers"
      description: What browsers are you seeing the issue on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Edge
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: What platform are you seeing the issue on?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: true
