name: Publish Firefox Addon

on:
  workflow_run:
    workflows: ["Create Release"]
    types: [completed]
    branches: [release]

permissions:
  contents: write

jobs:
  publish:
    name: Publish Firefox Addon
    # only run if the release workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: setup
        run: |
          npm ci
          sudo apt-get install jq zip
          mkdir -p release/chrome release/firefox
          echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      - id: lint
        run: npm run lint

      - name: Build Firefox Extension
        run: npm run build:firefox
    
      - name: Publish Mozilla Store
        run: |
          npx web-ext sign \
            --use-submission-api \
            --channel listed \
            --source-dir ./dist/firefox/ \
            --artifacts-dir ./release/firefox/ \
            --api-key ${{ secrets.WEB_EXT_API_KEY }} \
            --api-secret ${{ secrets.WEB_EXT_API_SECRET }}
